### ISSUE TITLE
Upload additional submission scripts

### ISSUE THREAD

**Issue by cilwerner** [HemeLB-dev/HemeLB-Carpentries#6]
PBS scripts are needed to reflect the different HPC systems. Ideally different submission scripts from the likes of SUMMIT, JURECA can be used and then edited accordingly so anyone viewing this can see submission scripts as they would when submitting on that system.

- [x] PBS script
- [x] SUMMIT job submission
- [x] JURECA job submission
- [x] ARCHER job submission

**Comment by cilwerner** [comment]
1 example of PBS script
2 SLURM examples
1 SUMMIT

**Comment by JonMcCullough** [comment]
I have added PBS files to the folders with example job files. As noted last week, the use of these will be dependent on a user's local system settings but they are a start. I will file a merge request shortly.
