### ISSUE TITLE
Plot and upload graphs for Practicals

### ISSUE THREAD

**Issue by cilwerner** [HemeLB-dev/HemeLB-Carpentries#7]
- [x] 5/6 example graphs with different scales for MCQs
- [x] Scalability plot MCQ, where is best scalability

**Comment by JonMcCullough** [comment]
Did we want these plots to be based on actual data? Or artificially constructed to illustrate a point?

**Comment by cilwerner** [comment]
Hi Jon,

We can have them artificially generated, if you are talking about the benchmarking exercises.

Chris.
________________________________
